---
spring:
  profiles: eureka1
  application:
    name: eureka
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jingxiansheng?serverTimezone=UTC
    username: root
    password: 123456
  security:
    user:
      name: linxd
      password: 123456

server:
  port: 8761

eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://linxd:123456@eureka2:8762/eureka/
    register-with-eureka: false
    fetch-registry: false

---
spring:
  profiles: eureka2
  application:
    name: eureka
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jingxiansheng?serverTimezone=UTC
    username: root
    password: 123456
  security:
    user:
      name: linxd
      password: 123456

server:
  port: 8762

eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://linxd:123456@eureka1:8761/eureka/
    register-with-eureka: false
    fetch-registry: false