
---
spring:
  profiles: eureka1
  application:
    name: eureka
  security:
    user:
      name: linxd
      password: 123456

server:
  port: 8761

eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://linxd:123456@eureka2:8762/eureka/
    register-with-eureka: false
    fetch-registry: false

---
spring:
  profiles: eureka2
  application:
    name: eureka
  security:
    user:
      name: linxd
      password: 123456

server:
  port: 8762

eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://linxd:123456@eureka1:8761/eureka/
    register-with-eureka: false
    fetch-registry: false