server:
  port: 9002

spring:
  application:
    name: loginandregister
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jingxiansheng?serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.190.143
    port: 7100
    password: 123456
    timeout: 2000
    jedis:
      pool:
        max-active: 30 # 连接池最大连接数
        max-wait: 10000 # 连接池最大阻塞等待时间
        max-idle: 30 # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接

    block-when-exhausted: true #自定义参数

eureka:
  client:
    service-url:
      defaultZone: http://linxd:123456@eureka1:8761/eureka/, http://linxd:123456@eureka2:8762/eureka/
