server:
  port: 9002

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: loginandregister
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jingxiansheng?serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.190.143
    port: 7100
    #password: 123456
    timeout: 2000



eureka:
  client:
    service-url:
      defaultZone: http://linxd:123456@eureka1:8761/eureka/, http://linxd:123456@eureka2:8762/eureka/
management:
  health:
    redis:
      enabled: false